### PR TITLE
Separate default header navbar in new components

### PR DESCRIPTION
**Pull request by mjsorribas**
These changes simplify the use for developers:

- LeftNavBarItem.vue: this file control the links items on the left.
- RightNavBarItem.vue: this file contains the element's items on the right.
- LogoNavBarItem.vue: this file contains the brand logo element's items.
- src/configs/leftNavBarItems.json: this file contains a json with the elements information to use with LeftNavBarItem component.  
- src/configs/logoNavBarItems.json: this file contains a json with the elements information to use with LogoNavBarItem component.  
- DefaultHeader.vue: this file was updated to use the new components

### CODE REVIEW

**Comment by woothu** [comment]
In my opinion, the header is more readable now and those changes just make it less flexible.

**Comment by mjsorribas** [comment]
With this changes you get benefits to develop more quickly, you can change the logo, the navigation bar links without touch one line of code, you only need to modify a config json file.

**Comment by mjsorribas** [comment]
> In my opinion, the header is more readable now and those changes just make it less flexible.

With this changes you get benefits to develop more quickly, you can change the logo, the navigation bar links without touch one line of code, you only need to modify a config json file.

**Comment by mjsorribas** [comment]
Hi @xidedix, what do you think about these changes?

**Pull request closed without merging**
